# NOTE: This Job requires permissions to read/write secrets in the cluster. This is taken care of via the ClusterRoleBinding
# created during the deployment of the GenevaServices chart. If we ever decide not to deploy GenevaServices first, or stop using
# it entirely, we'll need to copy that binding over here.

apiVersion: batch/v1
kind: Job
metadata:
  name: keyvaultagent
spec:
  backoffLimit: 1 # only attempt the job once
  template:
    metadata:
      labels:
        app: keyvaultagent
        aadpodidbinding: {{ .Values.metadata.aadpodidbinding }}
      annotations:
        timestamp: "{{ .Release.Time.Seconds }}"
    spec:
      containers:
      - name: keyvaultagent-global
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        env:
          - name: VAULT_BASE_URL
            value: {{ .Values.keyvaultagent.CertKeyVaultUrl | quote }}
          - name: SERVICE_PRINCIPLE_FILE_PATH
            value: /host-sp/azure.json
          - name: SECRETS_KEYS
            value: ""
          - name: PEMCERT_KEYS
            value: {{ .Values.keyvaultagent.ARMCertName | quote }}
          - name: TLS_KEYS
            value: {{ .Values.keyvaultagent.sslCertName | quote }}
          - name: CREATE_KUBERNETES_SECRETS
            value: "true"
          - name: SECRETS_NAMESPACE
            value: {{ .Values.keyvaultagent.Namespace | quote }}
        volumeMounts:
          - name: host-sp
            mountPath: /host-sp
            readOnly: true

      - name: keyvaultagent-region
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        env:
          - name: VAULT_BASE_URL
            value: {{ .Values.keyvaultagent.RegionKeyVaultUrl | quote }}
          - name: SERVICE_PRINCIPLE_FILE_PATH
            value: /host-sp/azure.json
          - name: SECRETS_KEYS
            value: ""
          - name: TLS_KEYS
            value: ""
          - name: CREATE_KUBERNETES_SECRETS
            value: "true"
          - name: SECRETS_NAMESPACE
            value: {{ .Values.keyvaultagent.Namespace | quote }}
        volumeMounts:
          - name: host-sp
            mountPath: /host-sp
            readOnly: true
      imagePullSecrets:
      - name: acrregistrykey

      restartPolicy: Never

      volumes:
        - name: host-sp
          hostPath:
            # this file contains the cluster service-principal, it exists on every node by default
            path: /etc/kubernetes