apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: keyvaultagent-secret-access-role
  namespace: {{ .Values.keyvaultagent.Namespace | quote }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - create
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: keyvaultagent-secret-access-rolebinding
  namespace: {{ .Values.keyvaultagent.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keyvaultagent-secret-access-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.keyvaultagent.Namespace | quote }}