{{ if eq .Values.configmap.Environment "Dev" }}
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: ccrp-ingress
  namespace: "{{ .Values.deployment.namespace }}"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
    - hosts:
      - "*.rp.kubernetesconfiguration-test.azure.com"
  rules:
    - http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: {{ .Values.deployment.servicename }}
              servicePort: {{ .Values.http.port }}
      host: "*.rp.kubernetesconfiguration-test.azure.com"
{{ end }}