apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.servicename }}
  namespace: "{{ .Values.deployment.namespace }}"
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: kubernetesconfiguration
spec:
  type: NodePort
  ports:
    - port: {{ .Values.http.port }}
      protocol: TCP
      name: http
      targetPort: {{ .Values.http.port }}
  selector:
    app: {{ .Values.deployment.servicename }}
    namespace: "{{ .Values.deployment.namespace }}"